In [1]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
flat = array.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
flat[:5]

array([1, 2, 3, 4, 5])

In [7]:
flat[5:]

array([6, 7, 8, 9])

In [8]:
flat[3:13]

array([4, 5, 6, 7, 8, 9])

In [9]:
flat[::2]

array([1, 3, 5, 7, 9])