In [1]:
#arr.dtype

import numpy as np

In [2]:
arr = np.array([23,4,5,6])


In [3]:
arr.dtype

dtype('int64')

In [5]:
arr.astype("float64")

array([23.,  4.,  5.,  6.])

In [6]:
arr.nbytes

32

In [7]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)


24
12


In [8]:
# also support complex no 


arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


In [3]:
# boradcasting


#pytho loops are slow 

#so to fix it we can use vectorization like we can diectly sat to arr that change ot power of two

import numpy as np
import time
start = time.time()

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)  # Output: [1, 4, 9, 16, 25]
end = time.time()

print(end - start)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]
0.0002694129943847656


In [5]:
#vectorized
import numpy as np
import time

start = time.time()
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]
end = time.time()

print(end-start)


[ 1  4  9 16 25]
0.00047850608825683594


In [ ]:
result + 10  #this is broadcasting : brodacating 10 is added to all elements without using extra memory


array([11, 14, 19, 26, 35])

In [7]:
# build in math funcs

import numpy as np

In [8]:
arr = np.array([1,2,3,4])

In [9]:
np.mean(arr)

np.float64(2.5)

In [10]:
np.std(arr)

np.float64(1.118033988749895)

In [12]:
np.var(arr)

np.float64(1.25)

In [14]:
np.percentile(arr,50)

np.float64(2.5)

In [15]:
np.argmin(arr)

np.int64(0)